# Generated by Django 3.2 on 2021-04-30 14:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('employee_type', models.CharField(choices=[('MAIN_SYSTEM_ADMINISTRATOR', 'Main administrator'), ('SYSTEM_ADMINISTRATOR', 'System administrator'), ('SENIOR_NETWORK_ENGINEER', 'Senior network engineer'), ('MIDDLE_NETWORK_ENGINEER', 'Middle network engineer'), ('JUNIOR_NETWORK_ENGINEER', 'Junior network engineer'), ('TECH_SUPPORT', 'Tech support')], max_length=250)),
                ('salary', models.PositiveIntegerField(default=0)),
                ('date_of_birth', models.DateField(default=datetime.date(2021, 4, 30))),
                ('provider_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='providers.provider')),
            ],
        ),
    ]
