# Generated by Django 3.2 on 2021-06-06 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_auto_20210503_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2021, 6, 6)),
        ),
    ]
