export const GET_PROVIDERS_LIST = 'GET_PROVIDERS_LIST';
export const GET_PROVIDER = 'GET_PROVIDER';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const ADD_PROVIDER = 'ADD_PROVIDER';
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';

export const GET_EMPLOYEES_LIST = 'GET_EMPLOYEES_LIST';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
