export const GET_PROVIDERS_LIST = 'GET_PROVIDERS_LIST';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const ADD_PROVIDER = 'ADD_PROVIDER';
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';
