
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_PROVIDERS_LIST = 'GET_PROVIDERS_LIST';
export const GET_PROVIDER = 'GET_PROVIDER';
export const DELETE_PROVIDER = 'DELETE_PROVIDER';
export const ADD_PROVIDER = 'ADD_PROVIDER';
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER';

export const GET_EMPLOYEES_LIST = 'GET_EMPLOYEES_LIST';
export const GET_EMPLOYEE = 'GET_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
